# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!

import grpc
from . import gamepad_pb2 as gamepad__pb2


class GamepadEventsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InitService = channel.unary_unary(
        '/grpc_client.GamepadEvents/InitService',
        request_serializer=gamepad__pb2.CallRover.SerializeToString,
        response_deserializer=gamepad__pb2.RoverFeedback.FromString,
        )
    self.ButtonEvent = channel.unary_unary(
        '/grpc_client.GamepadEvents/ButtonEvent',
        request_serializer=gamepad__pb2.Button.SerializeToString,
        response_deserializer=gamepad__pb2.ButtonFeedback.FromString,
        )
    self.TransmitLS = channel.stream_stream(
        '/grpc_client.GamepadEvents/TransmitLS',
        request_serializer=gamepad__pb2.LeftStick.SerializeToString,
        response_deserializer=gamepad__pb2.LeftStickFeedback.FromString,
        )
    self.TransmitRS = channel.stream_stream(
        '/grpc_client.GamepadEvents/TransmitRS',
        request_serializer=gamepad__pb2.RightStick.SerializeToString,
        response_deserializer=gamepad__pb2.RightStickFeedback.FromString,
        )
    self.TransmitLT = channel.stream_stream(
        '/grpc_client.GamepadEvents/TransmitLT',
        request_serializer=gamepad__pb2.LeftTrigger.SerializeToString,
        response_deserializer=gamepad__pb2.LeftTriggerFeedback.FromString,
        )
    self.TransmitRT = channel.stream_stream(
        '/grpc_client.GamepadEvents/TransmitRT',
        request_serializer=gamepad__pb2.RightTrigger.SerializeToString,
        response_deserializer=gamepad__pb2.RightTriggerFeedback.FromString,
        )


class GamepadEventsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def InitService(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ButtonEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransmitLS(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransmitRS(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransmitLT(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransmitRT(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GamepadEventsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InitService': grpc.unary_unary_rpc_method_handler(
          servicer.InitService,
          request_deserializer=gamepad__pb2.CallRover.FromString,
          response_serializer=gamepad__pb2.RoverFeedback.SerializeToString,
      ),
      'ButtonEvent': grpc.unary_unary_rpc_method_handler(
          servicer.ButtonEvent,
          request_deserializer=gamepad__pb2.Button.FromString,
          response_serializer=gamepad__pb2.ButtonFeedback.SerializeToString,
      ),
      'TransmitLS': grpc.stream_stream_rpc_method_handler(
          servicer.TransmitLS,
          request_deserializer=gamepad__pb2.LeftStick.FromString,
          response_serializer=gamepad__pb2.LeftStickFeedback.SerializeToString,
      ),
      'TransmitRS': grpc.stream_stream_rpc_method_handler(
          servicer.TransmitRS,
          request_deserializer=gamepad__pb2.RightStick.FromString,
          response_serializer=gamepad__pb2.RightStickFeedback.SerializeToString,
      ),
      'TransmitLT': grpc.stream_stream_rpc_method_handler(
          servicer.TransmitLT,
          request_deserializer=gamepad__pb2.LeftTrigger.FromString,
          response_serializer=gamepad__pb2.LeftTriggerFeedback.SerializeToString,
      ),
      'TransmitRT': grpc.stream_stream_rpc_method_handler(
          servicer.TransmitRT,
          request_deserializer=gamepad__pb2.RightTrigger.FromString,
          response_serializer=gamepad__pb2.RightTriggerFeedback.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc_client.GamepadEvents', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
