# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamepad.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gamepad.proto',
  package='grpc_client',
  syntax='proto3',
  serialized_options=b'\242\002\005ORION',
  serialized_pb=b'\n\rgamepad.proto\x12\x0bgrpc_client\"\"\n\tCallRover\x12\x15\n\rhello_message\x18\x01 \x01(\t\"\'\n\rRoverFeedback\x12\x16\n\x0ehello_response\x18\x01 \x01(\t\"\x1a\n\x06\x42utton\x12\x10\n\x08\x62tn_name\x18\x01 \x01(\t\"+\n\x0e\x42uttonFeedback\x12\x19\n\x11\x62tn_name_received\x18\x01 \x01(\t\"/\n\tLeftStick\x12\x10\n\x08x_offset\x18\x01 \x01(\x05\x12\x10\n\x08y_offset\x18\x02 \x01(\x05\"[\n\x11LeftStickFeedback\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x19\n\x11x_offset_received\x18\x02 \x01(\x05\x12\x19\n\x11y_offset_received\x18\x03 \x01(\x05\"0\n\nRightStick\x12\x10\n\x08x_offset\x18\x01 \x01(\x05\x12\x10\n\x08y_offset\x18\x02 \x01(\x05\"\\\n\x12RightStickFeedback\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x19\n\x11x_offset_received\x18\x02 \x01(\x05\x12\x19\n\x11y_offset_received\x18\x03 \x01(\x05\"\x1f\n\x0bLeftTrigger\x12\x10\n\x08z_offset\x18\x01 \x01(\x05\"B\n\x13LeftTriggerFeedback\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x19\n\x11z_offset_received\x18\x02 \x01(\x05\" \n\x0cRightTrigger\x12\x10\n\x08z_offset\x18\x01 \x01(\x05\"C\n\x14RightTriggerFeedback\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x19\n\x11z_offset_received\x18\x02 \x01(\x05\x32\xd3\x03\n\rGamepadEvents\x12\x43\n\x0bInitService\x12\x16.grpc_client.CallRover\x1a\x1a.grpc_client.RoverFeedback\"\x00\x12\x41\n\x0b\x42uttonEvent\x12\x13.grpc_client.Button\x1a\x1b.grpc_client.ButtonFeedback\"\x00\x12J\n\nTransmitLS\x12\x16.grpc_client.LeftStick\x1a\x1e.grpc_client.LeftStickFeedback\"\x00(\x01\x30\x01\x12L\n\nTransmitRS\x12\x17.grpc_client.RightStick\x1a\x1f.grpc_client.RightStickFeedback\"\x00(\x01\x30\x01\x12N\n\nTransmitLT\x12\x18.grpc_client.LeftTrigger\x1a .grpc_client.LeftTriggerFeedback\"\x00(\x01\x30\x01\x12P\n\nTransmitRT\x12\x19.grpc_client.RightTrigger\x1a!.grpc_client.RightTriggerFeedback\"\x00(\x01\x30\x01\x42\x08\xa2\x02\x05ORIONb\x06proto3'
)




_CALLROVER = _descriptor.Descriptor(
  name='CallRover',
  full_name='grpc_client.CallRover',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hello_message', full_name='grpc_client.CallRover.hello_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=64,
)


_ROVERFEEDBACK = _descriptor.Descriptor(
  name='RoverFeedback',
  full_name='grpc_client.RoverFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hello_response', full_name='grpc_client.RoverFeedback.hello_response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=105,
)


_BUTTON = _descriptor.Descriptor(
  name='Button',
  full_name='grpc_client.Button',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='btn_name', full_name='grpc_client.Button.btn_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=133,
)


_BUTTONFEEDBACK = _descriptor.Descriptor(
  name='ButtonFeedback',
  full_name='grpc_client.ButtonFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='btn_name_received', full_name='grpc_client.ButtonFeedback.btn_name_received', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=178,
)


_LEFTSTICK = _descriptor.Descriptor(
  name='LeftStick',
  full_name='grpc_client.LeftStick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_offset', full_name='grpc_client.LeftStick.x_offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_offset', full_name='grpc_client.LeftStick.y_offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=227,
)


_LEFTSTICKFEEDBACK = _descriptor.Descriptor(
  name='LeftStickFeedback',
  full_name='grpc_client.LeftStickFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='grpc_client.LeftStickFeedback.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_offset_received', full_name='grpc_client.LeftStickFeedback.x_offset_received', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_offset_received', full_name='grpc_client.LeftStickFeedback.y_offset_received', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=320,
)


_RIGHTSTICK = _descriptor.Descriptor(
  name='RightStick',
  full_name='grpc_client.RightStick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_offset', full_name='grpc_client.RightStick.x_offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_offset', full_name='grpc_client.RightStick.y_offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=370,
)


_RIGHTSTICKFEEDBACK = _descriptor.Descriptor(
  name='RightStickFeedback',
  full_name='grpc_client.RightStickFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='grpc_client.RightStickFeedback.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_offset_received', full_name='grpc_client.RightStickFeedback.x_offset_received', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_offset_received', full_name='grpc_client.RightStickFeedback.y_offset_received', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=464,
)


_LEFTTRIGGER = _descriptor.Descriptor(
  name='LeftTrigger',
  full_name='grpc_client.LeftTrigger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='z_offset', full_name='grpc_client.LeftTrigger.z_offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=497,
)


_LEFTTRIGGERFEEDBACK = _descriptor.Descriptor(
  name='LeftTriggerFeedback',
  full_name='grpc_client.LeftTriggerFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='grpc_client.LeftTriggerFeedback.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_offset_received', full_name='grpc_client.LeftTriggerFeedback.z_offset_received', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=565,
)


_RIGHTTRIGGER = _descriptor.Descriptor(
  name='RightTrigger',
  full_name='grpc_client.RightTrigger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='z_offset', full_name='grpc_client.RightTrigger.z_offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=599,
)


_RIGHTTRIGGERFEEDBACK = _descriptor.Descriptor(
  name='RightTriggerFeedback',
  full_name='grpc_client.RightTriggerFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='grpc_client.RightTriggerFeedback.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_offset_received', full_name='grpc_client.RightTriggerFeedback.z_offset_received', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=668,
)

DESCRIPTOR.message_types_by_name['CallRover'] = _CALLROVER
DESCRIPTOR.message_types_by_name['RoverFeedback'] = _ROVERFEEDBACK
DESCRIPTOR.message_types_by_name['Button'] = _BUTTON
DESCRIPTOR.message_types_by_name['ButtonFeedback'] = _BUTTONFEEDBACK
DESCRIPTOR.message_types_by_name['LeftStick'] = _LEFTSTICK
DESCRIPTOR.message_types_by_name['LeftStickFeedback'] = _LEFTSTICKFEEDBACK
DESCRIPTOR.message_types_by_name['RightStick'] = _RIGHTSTICK
DESCRIPTOR.message_types_by_name['RightStickFeedback'] = _RIGHTSTICKFEEDBACK
DESCRIPTOR.message_types_by_name['LeftTrigger'] = _LEFTTRIGGER
DESCRIPTOR.message_types_by_name['LeftTriggerFeedback'] = _LEFTTRIGGERFEEDBACK
DESCRIPTOR.message_types_by_name['RightTrigger'] = _RIGHTTRIGGER
DESCRIPTOR.message_types_by_name['RightTriggerFeedback'] = _RIGHTTRIGGERFEEDBACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CallRover = _reflection.GeneratedProtocolMessageType('CallRover', (_message.Message,), {
  'DESCRIPTOR' : _CALLROVER,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.CallRover)
  })
_sym_db.RegisterMessage(CallRover)

RoverFeedback = _reflection.GeneratedProtocolMessageType('RoverFeedback', (_message.Message,), {
  'DESCRIPTOR' : _ROVERFEEDBACK,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.RoverFeedback)
  })
_sym_db.RegisterMessage(RoverFeedback)

Button = _reflection.GeneratedProtocolMessageType('Button', (_message.Message,), {
  'DESCRIPTOR' : _BUTTON,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.Button)
  })
_sym_db.RegisterMessage(Button)

ButtonFeedback = _reflection.GeneratedProtocolMessageType('ButtonFeedback', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONFEEDBACK,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.ButtonFeedback)
  })
_sym_db.RegisterMessage(ButtonFeedback)

LeftStick = _reflection.GeneratedProtocolMessageType('LeftStick', (_message.Message,), {
  'DESCRIPTOR' : _LEFTSTICK,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.LeftStick)
  })
_sym_db.RegisterMessage(LeftStick)

LeftStickFeedback = _reflection.GeneratedProtocolMessageType('LeftStickFeedback', (_message.Message,), {
  'DESCRIPTOR' : _LEFTSTICKFEEDBACK,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.LeftStickFeedback)
  })
_sym_db.RegisterMessage(LeftStickFeedback)

RightStick = _reflection.GeneratedProtocolMessageType('RightStick', (_message.Message,), {
  'DESCRIPTOR' : _RIGHTSTICK,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.RightStick)
  })
_sym_db.RegisterMessage(RightStick)

RightStickFeedback = _reflection.GeneratedProtocolMessageType('RightStickFeedback', (_message.Message,), {
  'DESCRIPTOR' : _RIGHTSTICKFEEDBACK,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.RightStickFeedback)
  })
_sym_db.RegisterMessage(RightStickFeedback)

LeftTrigger = _reflection.GeneratedProtocolMessageType('LeftTrigger', (_message.Message,), {
  'DESCRIPTOR' : _LEFTTRIGGER,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.LeftTrigger)
  })
_sym_db.RegisterMessage(LeftTrigger)

LeftTriggerFeedback = _reflection.GeneratedProtocolMessageType('LeftTriggerFeedback', (_message.Message,), {
  'DESCRIPTOR' : _LEFTTRIGGERFEEDBACK,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.LeftTriggerFeedback)
  })
_sym_db.RegisterMessage(LeftTriggerFeedback)

RightTrigger = _reflection.GeneratedProtocolMessageType('RightTrigger', (_message.Message,), {
  'DESCRIPTOR' : _RIGHTTRIGGER,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.RightTrigger)
  })
_sym_db.RegisterMessage(RightTrigger)

RightTriggerFeedback = _reflection.GeneratedProtocolMessageType('RightTriggerFeedback', (_message.Message,), {
  'DESCRIPTOR' : _RIGHTTRIGGERFEEDBACK,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:grpc_client.RightTriggerFeedback)
  })
_sym_db.RegisterMessage(RightTriggerFeedback)


DESCRIPTOR._options = None

_GAMEPADEVENTS = _descriptor.ServiceDescriptor(
  name='GamepadEvents',
  full_name='grpc_client.GamepadEvents',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=671,
  serialized_end=1138,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitService',
    full_name='grpc_client.GamepadEvents.InitService',
    index=0,
    containing_service=None,
    input_type=_CALLROVER,
    output_type=_ROVERFEEDBACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ButtonEvent',
    full_name='grpc_client.GamepadEvents.ButtonEvent',
    index=1,
    containing_service=None,
    input_type=_BUTTON,
    output_type=_BUTTONFEEDBACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TransmitLS',
    full_name='grpc_client.GamepadEvents.TransmitLS',
    index=2,
    containing_service=None,
    input_type=_LEFTSTICK,
    output_type=_LEFTSTICKFEEDBACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TransmitRS',
    full_name='grpc_client.GamepadEvents.TransmitRS',
    index=3,
    containing_service=None,
    input_type=_RIGHTSTICK,
    output_type=_RIGHTSTICKFEEDBACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TransmitLT',
    full_name='grpc_client.GamepadEvents.TransmitLT',
    index=4,
    containing_service=None,
    input_type=_LEFTTRIGGER,
    output_type=_LEFTTRIGGERFEEDBACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TransmitRT',
    full_name='grpc_client.GamepadEvents.TransmitRT',
    index=5,
    containing_service=None,
    input_type=_RIGHTTRIGGER,
    output_type=_RIGHTTRIGGERFEEDBACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMEPADEVENTS)

DESCRIPTOR.services_by_name['GamepadEvents'] = _GAMEPADEVENTS

# @@protoc_insertion_point(module_scope)
